FROM nats

COPY nats-server.conf /etc/nats/nats-server.conf
# COPY docker-entrypoint.sh /usr/local/bin
EXPOSE 4222 8222 6222
# ENTRYPOINT ["docker-entrypoint.sh"]
# CMD ["nats-server", "--config", "/etc/nats/nats-server.conf"]

# Jarek (Scumbag) +48606255495
